name: weather_app
description: A modern Flutter weather app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # For API calls
  geolocator: ^13.0.1 # For device location
  intl: ^0.19.0 # For date formatting
  flutter_spinkit: ^5.2.0 # For loading animations
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shared_preferences: ^2.2.2
  flutter_lints: ^3.0.2
  fl_chart: ^0.69.0
  glassmorphism: ^3.0.0
  lottie: ^2.4.0
  google_fonts: ^6.2.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/ # Create an 'assets' folder for weather icons (download free icons from https://openweathermap.org/weather-conditions or use placeholders)
    - assets/lottie/sunny.json
    - assets/lottie/rain.json
    - assets/lottie/thunder.json
    - assets/lottie/snow.json
    - assets/lottie/cloudy.json
    - assets/lottie/fog.json
